steps:
- name: 'node:alpine'
  args: ["/bin/bash", "-c", 'npm install && npm test']

# Uses the docker build step to build an image called my-image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

# Uses the kubectl tool to update the deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args: ["/bin/bash", "-c", "sed -e 's~<PROJECT_ID>~$PROJECT_ID~g' kubernetes.yaml | sed -e 's~<REPO_NAME>~$REPO_NAME~g' | sed -e 's~<COMMIT_SHA>~$COMMIT_SHA~g' | kubectl apply -f -"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-test'

# my-image is pushed to Container Registry
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'